uval=[ones(1,50)*0.5 ones(1,50)*2 ones(1,50)*0.5 ones(1,50)*2];
data=system_simulator(5,uval');
plot(data);
m=10;
N=300;
a=0.5;
b=1;
uid=PRBS(N,m,a,b);
figure()
stairs(uid);
data2=system_simulator(5,uid');
figure()
plot(data2);
model=arx(data2,[20,20,1]);
figure()
compare(model,data);
uid=detrend(uid);
r=xcorr(uid);
figure()
plot(r);
%%
uid=detrend(uid);
r=xcorr(uid);
plot(r);
m=10;
N=300;
a=0.5;
b=1;
uid=PRBS(N,m,a,b);
figure()
stairs(uid);
data2=system_simulator(5,uid');
model1=arx(data2,[10,10,1]);
figure()
compare(model1,data);
r=xcorr(uid);
figure()
plot(r);